# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1430423511);
user_pref("app.update.lastUpdateTime.background-update-timer", 1430471047);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1430423636);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1430470350);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.lastAppVersion", "2.0");
user_pref("extensions.lastPlatformVersion", "37.0.2");
user_pref("extensions.shownSelectionUI", true);
user_pref("general.useragent.locale", "de-DE");
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.importedState", true);
user_pref("toolkit.telemetry.previousBuildID", "16062008");
