pref("app.update.auto", false);
pref("app.update.enabled", false);
pref("toolkit.defaultChromeURI", "chrome://seb/content/seb.xul");
pref("toolkit.singletonWindowType", "main");
pref("accessibility.browsewithcaret_shortcut.enabled", false);
pref("browser.chromeURL", "chrome://seb/content/seb.xul");
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.download.manager.retention", 0);
pref("browser.download.manager.useWindow", false);
pref("browser.link.open_newwindow", 2);
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.zoom.full", true);
pref("extensions.update.enabled", false);
pref("mousewheel.withaltkey.action", 3);
pref("mousewheel.withcontrolkey.action", 1);
pref("network.cookie.prefsMigrated", true);
pref("privacy.popups.firstTime", false);
pref("privacy.popups.policy", 1);
pref("security.default_personal_cert", "Select Automatically");

