pref("app.update.auto", false);
pref("app.update.enabled", false);
pref("app.support.baseURL", "");
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.server", "");
pref("toolkit.telemetry.server_owner", "");
pref("experiments.manifest.uri", "");
pref("toolkit.telemetry.cachedClientID", "");
pref("toolkit.telemetry.archive.enabled", false);
pref("toolkit.telemetry.infoURL","");
pref("toolkit.telemetry.optoutSample",false);
pref("toolkit.telemetry.previousBuildID","");
pref("toolkit.telemetry.reportingpolicy.firstRun",false);
pref("toolkit.telemetry.unified",false);
pref("toolkit.telemetry.unifiedIsOptIn",false);
pref("accessibility.browsewithcaret_shortcut.enabled", false);
pref("extensions.update.enabled", false);
pref("network.cookie.prefsMigrated", true);
pref("gecko.handlerService.allowRegisterFromDifferentHost", true);
pref("intl.ime.nstextinput.enable", true);
